#!/usr/bin/env bash
# Install HAProxy for load balancing

sudo apt-get -y update
sudo ufw allow 'ssh'
sudo ufw allow 'OpenSSH'
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*
sudo cp -a /etc/haproxy/haproxy.cfg{,.old}
echo "frontend  bigmuse-frontend
        bind *:80
        mode http
        default_backend bigmuse-backend
backend bigmuse-backend
        balance roundrobin
        server 483547-web-01 100.27.11.204:80 check
        server 483547-web-02 3.85.41.254:80 check
" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
sudo ufw enable
sudo ufw status
